### ISSUE TITLE
SIGN-UP

### ISSUE THREAD

**Issue by ySharma0** [UCMRoboticsFoodRobot/WebApp#4]
- [x] GOOGLE SIGN - UP - API ( O-AUTH )
- [x] EMAIL SIGN-UP API
- - [x] E-MAIL CONFORMATION
- [x] USER ROLES + Permissions:
- - [x] CUSTOMER
- - [x] ENGINEER
- - [x] ADMIN
- - [x] SUPPLIER

**Comment by ySharma0** [comment]
@BusherBridi Can you review this

**Comment by BusherBridi** [comment]
Please make sure this is linked correctly to the front end component. Fix and ask for another review.
